# Generated by Django 3.2.9 on 2022-02-17 16:16

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0003_auto_20220217_1012'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='likes',
            field=models.ManyToManyField(blank=True, default=0, to=settings.AUTH_USER_MODEL),
        ),
    ]
